#!/bin/bash

# if [[ $SSHPASS == "" ]]; then
# 	cat "Error: environment variable SSHPASS not set!" 0>&2
# 	exit
# fi

for ip in 152 228 229 235 18 22 36 39 42; do
	ping -c1 -W5 "172.16.200.$ip"
	if [[ $? == 0 ]]; then
		basename="proxmox-172.16.200.$ip"
		if [[ ! -d "$basename" ]]
		then
			mkdir -p "$basename/etc/network"
			mkdir -p "$basename/etc/pve"
		fi

		scp root@172.16.200.$ip:"/etc/hosts" "$basename/etc"
		scp root@172.16.200.$ip:"/etc/network/interfaces" "$basename/etc/network/"
		scp root@172.16.200.$ip:"/etc/resolv.conf" "$basename/etc/"
		scp -r root@172.16.200.$ip:"/etc/pve/qemu-server" "$basename/etc/"
		scp -r root@172.16.200.$ip:"/etc/pve/lxc" "$basename/etc/"

	fi
done
